# Configuration file for cat-clipboard-launcher
# クリップボードランチャー設定ファイル

# 一時ファイルパス（クリップボード内容を保存）
# Windowsパス形式（スラッシュまたはバックスラッシュ）
clipboard_temp_file = "C:/temp/clipboard_content.txt"

# アプリケーション出力をクリップボードに書き戻すかどうか（デフォルト: true）
# When true, if a pattern specifies output_file, the content will be written back to clipboard
write_output_to_clipboard = true

# パターン定義（配列形式）
[[patterns]]
name = "URL"
regex = "^https?://.*"
command = "start chrome.exe {CLIPBOARD_FILE}"

[[patterns]]
name = "ローカルファイルパス"
regex = "^[A-Z]:\\\\.+"
command = "explorer.exe /select,{CLIPBOARD_FILE}"

[[patterns]]
name = "メールアドレス"
regex = "^[\\w.+-]+@[\\w.-]+\\.[a-z]{2,}$"
command = "start outlook.exe /a {CLIPBOARD_FILE}"

[[patterns]]
name = "GitHub Issue"
regex = "#\\d+"
command = "notepad.exe {CLIPBOARD_FILE}"

[[patterns]]
name = "カスタムスクリプト"
regex = "^CUSTOM:"
command = "python.exe process.py --input {CLIPBOARD_FILE} --output {CLIPBOARD_FILE}.result"
output_file = "{CLIPBOARD_FILE}.result"  # Optional: if specified, content is written back to clipboard
