# Configuration file for cat-clipboard-launcher
# クリップボードランチャー設定ファイル

# 一時ファイルパス（クリップボード内容を保存）
# オプション：省略した場合、カレントディレクトリの clipboard_content.txt を使用
# 相対パスまたは絶対パス
# clipboard_temp_file = "./clipboard_content.txt"

# パターン定義（配列形式）
[[patterns]]
name = "URL"
regex = "^https?://.*"
command = "start chrome.exe {CLIPBOARD_FILE}"

[[patterns]]
name = "ローカルファイルパス"
regex = "^[A-Z]:\\\\.+"
command = "explorer.exe /select,{CLIPBOARD_FILE}"

[[patterns]]
name = "メールアドレス"
regex = "^[\\w.+-]+@[\\w.-]+\\.[a-z]{2,}$"
command = "start outlook.exe /a {CLIPBOARD_FILE}"

[[patterns]]
name = "GitHub Issue"
regex = "#\\d+"
command = "notepad.exe {CLIPBOARD_FILE}"

[[patterns]]
name = "カスタムスクリプト"
regex = "^CUSTOM:"
command = "python.exe process.py --input {CLIPBOARD_FILE} --output {CLIPBOARD_FILE}.result"
output_file = "{CLIPBOARD_FILE}.result"
write_output_to_clipboard = true  # Optional: default is false. Set to true to write output back to clipboard
